name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Compile the binary
        run: |
          make bin/goldpinger
          ./bin/goldpinger -h
      - name: Build the Docker image
        run: |
          make build
